export const BankingTestData = `<?xml version="1.0" encoding="utf-8"?>
<passwordfile xmlns="https://www.password-depot.de/schemas/passwordfile/17.0/passwordfile.xsd">
    <header>
        <application>Password Depot</application>
        <version>17.0.0</version>
        <comments></comments>
        <hint></hint>
        <fingerprint>CCDA8015-7F21-4344-BDF0-9EA6AF8AE31D</fingerprint>
        <datetime fmt="dd.mm.yyyy hh:mm:ss">12.05.2025 15:16:11</datetime>
        <encrypted>False</encrypted>
        <backupinterval>0</backupinterval>
        <lastbackup fmt="dd.mm.yyyy hh:mm:ss">30.12.1899 00:00:00</lastbackup>
        <hash></hash>
    </header>
    <passwords>
        <group name="tempDB" fingerprint="CCDA8015-7F21-4344-BDF0-9EA6AF8AE31D">            
            <item>
                <description>banking type</description>
                <type>5</type>
                <password>somePassword</password>
                <username>someUser</username>
                <url>some-bank.com</url>
                <comment>someNote</comment>
                <lastmodified fmt="dd.mm.yyyy hh:mm:ss">12.05.2025 15:11:29</lastmodified>
                <expirydate fmt="dd.mm.yyyy">02.05.2027</expirydate>
                <importance>1</importance>
                <fingerprint>DEB91652-52C6-402E-9D44-3557829BC6DF</fingerprint>
                <template>&lt;USER&gt;&lt;TAB&gt;&lt;PASS&gt;&lt;ENTER&gt;</template>
                <imageindex>127</imageindex>
                <imagecustom>0</imagecustom>
                <wndtitle></wndtitle>
                <paramstr></paramstr>
                <category>Allgemein</category>
                <custombrowser></custombrowser>
                <autocompletemethod>0</autocompletemethod>
                <loginid></loginid>
                <passid></passid>
                <created fmt="dd.mm.yyyy hh:mm:ss">12.05.2025 15:09:17</created>
                <lastaccessed fmt="dd.mm.yyyy hh:mm:ss">12.05.2025 15:09:17</lastaccessed>
                <donotaddon>0</donotaddon>
                <markassafe>0</markassafe>
                <safemode>0</safemode>
                <rndtype>1</rndtype>
                <rndcustom></rndcustom>
                <usagecount>0</usagecount>
                <keephistory>2</keephistory>
                <tags></tags>
                <author>DJSMI</author>
                <ownerid></ownerid>
                <warnmsg></warnmsg>
                <warnlvl>0</warnlvl>
                <warnverify></warnverify>
                <serverrqrd>0</serverrqrd>
                <secret></secret>
                <istemplate>0</istemplate>
                <infotemplate></infotemplate>
                <usetabs>161</usetabs>
                <islink>0</islink>
                <linkeditem></linkeditem>
                <customfields>
                    <field>
                        <name>IDS_ECHolder</name>
                        <value>account holder</value>
                        <visible>-1</visible>
                        <kind>0</kind>
                        <type>0</type>
                    </field>
                    <field>
                        <name>IDS_ECAccountNumber</name>
                        <value>1234567890</value>
                        <visible>-1</visible>
                        <kind>0</kind>
                        <type>0</type>
                    </field>
                    <field>
                        <name>IDS_ECBLZ</name>
                        <value>12345678</value>
                        <visible>-1</visible>
                        <kind>0</kind>
                        <type>0</type>
                    </field>
                    <field>
                        <name>IDS_ECBankName</name>
                        <value>someBank</value>
                        <visible>-1</visible>
                        <kind>0</kind>
                        <type>0</type>
                    </field>
                    <field>
                        <name>IDS_ECBIC</name>
                        <value>bic</value>
                        <visible>-1</visible>
                        <kind>0</kind>
                        <type>0</type>
                    </field>
                    <field>
                        <name>IDS_ECIBAN</name>
                        <value>iban</value>
                        <visible>-1</visible>
                        <kind>0</kind>
                        <type>0</type>
                    </field>
                    <field>
                        <name>IDS_ECCardNumber</name>
                        <value>12345678</value>
                        <visible>-1</visible>
                        <kind>0</kind>
                        <type>10</type>
                    </field>
                    <field>
                        <name>IDS_ECPhone</name>
                        <value>0049</value>
                        <visible>0</visible>
                        <kind>0</kind>
                        <type>0</type>
                    </field>
                    <field>
                        <name>IDS_ECLegitimacyID</name>
                        <value>1234</value>
                        <visible>-1</visible>
                        <kind>0</kind>
                        <type>0</type>
                    </field>
                    <field>
                        <name>IDS_ECPIN</name>
                        <value>123</value>
                        <visible>0</visible>
                        <kind>0</kind>
                        <type>1</type>
                    </field>
                </customfields>
                <tans>
                    <tan>
                        <number>1</number>
                        <value>1234</value>
                        <used fmt="dd.mm.yyyy hh:mm:ss">12.05.2025 15:10:54</used>
                        <amount> 100,00</amount>
                        <comment>some TAN note</comment>
                        <ccode>123</ccode>
                    </tan>
                    <tan>
                        <number>2</number>
                        <value>4321</value>
                        <amount> 0,00</amount>
                        <comment></comment>
                        <ccode></ccode>
                    </tan>
                </tans>
                <hitems>
                    <hitem>
                        <description>banking type</description>
                        <type>5</type>
                        <password>somePassword</password>
                        <username>someUser</username>
                        <url>some-bank.com</url>
                        <comment>someNote</comment>
                        <lastmodified fmt="dd.mm.yyyy hh:mm:ss">12.05.2025 15:10:35</lastmodified>
                        <expirydate fmt="dd.mm.yyyy">02.05.2027</expirydate>
                        <importance>1</importance>
                        <fingerprint>DEB91652-52C6-402E-9D44-3557829BC6DF</fingerprint>
                        <template>&lt;USER&gt;&lt;TAB&gt;&lt;PASS&gt;&lt;ENTER&gt;</template>
                        <imageindex>127</imageindex>
                        <imagecustom>0</imagecustom>
                        <wndtitle></wndtitle>
                        <paramstr></paramstr>
                        <category>Allgemein</category>
                        <custombrowser></custombrowser>
                        <autocompletemethod>0</autocompletemethod>
                        <loginid></loginid>
                        <passid></passid>
                        <created fmt="dd.mm.yyyy hh:mm:ss">12.05.2025 15:09:17</created>
                        <lastaccessed fmt="dd.mm.yyyy hh:mm:ss">12.05.2025 15:09:17</lastaccessed>
                        <donotaddon>0</donotaddon>
                        <markassafe>0</markassafe>
                        <safemode>0</safemode>
                        <rndtype>1</rndtype>
                        <rndcustom></rndcustom>
                        <usagecount>0</usagecount>
                        <keephistory>2</keephistory>
                        <tags></tags>
                        <author>DJSMI</author>
                        <ownerid></ownerid>
                        <warnmsg></warnmsg>
                        <warnlvl>0</warnlvl>
                        <warnverify></warnverify>
                        <serverrqrd>0</serverrqrd>
                        <secret></secret>
                        <istemplate>0</istemplate>
                        <infotemplate></infotemplate>
                        <usetabs>161</usetabs>
                        <islink>0</islink>
                        <linkeditem></linkeditem>
                        <customfields>
                            <field>
                                <name>IDS_ECHolder</name>
                                <value>account holder</value>
                                <visible>-1</visible>
                                <kind>0</kind>
                                <type>0</type>
                            </field>
                            <field>
                                <name>IDS_ECAccountNumber</name>
                                <value>1234567890</value>
                                <visible>-1</visible>
                                <kind>0</kind>
                                <type>0</type>
                            </field>
                            <field>
                                <name>IDS_ECBLZ</name>
                                <value>12345678</value>
                                <visible>-1</visible>
                                <kind>0</kind>
                                <type>0</type>
                            </field>
                            <field>
                                <name>IDS_ECBankName</name>
                                <value>someBank</value>
                                <visible>-1</visible>
                                <kind>0</kind>
                                <type>0</type>
                            </field>
                            <field>
                                <name>IDS_ECBIC</name>
                                <value>bic</value>
                                <visible>-1</visible>
                                <kind>0</kind>
                                <type>0</type>
                            </field>
                            <field>
                                <name>IDS_ECIBAN</name>
                                <value>iban</value>
                                <visible>-1</visible>
                                <kind>0</kind>
                                <type>0</type>
                            </field>
                            <field>
                                <name>IDS_ECCardNumber</name>
                                <value>12345678</value>
                                <visible>-1</visible>
                                <kind>0</kind>
                                <type>10</type>
                            </field>
                            <field>
                                <name>IDS_ECPhone</name>
                                <value>0049</value>
                                <visible>0</visible>
                                <kind>0</kind>
                                <type>0</type>
                            </field>
                            <field>
                                <name>IDS_ECLegitimacyID</name>
                                <value>1234</value>
                                <visible>-1</visible>
                                <kind>0</kind>
                                <type>0</type>
                            </field>
                            <field>
                                <name>IDS_ECPIN</name>
                                <value>123</value>
                                <visible>0</visible>
                                <kind>0</kind>
                                <type>1</type>
                            </field>
                        </customfields>
                    </hitem>
                </hitems>
            </item>
        </group>
    </passwords>
    <recyclebin>
    </recyclebin>
    <infotemplates>
    </infotemplates>
    <favorites>
        QUY3NEZGODYtRkUzOS00NTg0LThFOTYtRkU5NTBDMjg5REY4DQo=
    </favorites>
    <sitestoignore>

    </sitestoignore>
    <categories>
        QWxsZ2VtZWluDQpIb21lIEJhbmtpbmcNCkludGVybmV0DQpQcml2YXQNCldpbmRvd3MNCg==
    </categories>
</passwordfile>`;
