export const IdentityTestData = `<?xml version="1.0" encoding="utf-8"?>
<passwordfile xmlns="https://www.password-depot.de/schemas/passwordfile/17.0/passwordfile.xsd">
    <header>
        <application>Password Depot</application>
        <version>17.0.0</version>
        <comments></comments>
        <hint></hint>
        <fingerprint>CCDA8015-7F21-4344-BDF0-9EA6AF8AE31D</fingerprint>
        <datetime fmt="dd.mm.yyyy hh:mm:ss">12.05.2025 15:16:11</datetime>
        <encrypted>False</encrypted>
        <backupinterval>0</backupinterval>
        <lastbackup fmt="dd.mm.yyyy hh:mm:ss">30.12.1899 00:00:00</lastbackup>
        <hash></hash>
    </header>
    <passwords>
        <group name="tempDB" fingerprint="CCDA8015-7F21-4344-BDF0-9EA6AF8AE31D">
            <item>
                <description>identity type</description>
                <type>3</type>
                <password></password>
                <username>account-name/id</username>
                <url>website</url>
                <comment>someNote</comment>
                <lastmodified fmt="dd.mm.yyyy hh:mm:ss">12.05.2025 15:14:33</lastmodified>
                <expirydate fmt="dd.mm.yyyy">00.00.0000</expirydate>
                <importance>1</importance>
                <fingerprint>0E6085E9-7560-4826-814E-EFE1724E1377</fingerprint>
                <template></template>
                <imageindex>129</imageindex>
                <imagecustom>0</imagecustom>
                <wndtitle></wndtitle>
                <paramstr></paramstr>
                <category>Allgemein</category>
                <custombrowser></custombrowser>
                <autocompletemethod>0</autocompletemethod>
                <loginid></loginid>
                <passid></passid>
                <created fmt="dd.mm.yyyy hh:mm:ss">12.05.2025 15:12:52</created>
                <lastaccessed fmt="dd.mm.yyyy hh:mm:ss">12.05.2025 15:12:52</lastaccessed>
                <donotaddon>0</donotaddon>
                <markassafe>0</markassafe>
                <safemode>0</safemode>
                <rndtype>1</rndtype>
                <rndcustom></rndcustom>
                <usagecount>0</usagecount>
                <keephistory>2</keephistory>
                <tags></tags>
                <author>DJSMI</author>
                <ownerid></ownerid>
                <warnmsg></warnmsg>
                <warnlvl>0</warnlvl>
                <warnverify></warnverify>
                <serverrqrd>0</serverrqrd>
                <secret></secret>
                <istemplate>0</istemplate>
                <infotemplate></infotemplate>
                <usetabs>161</usetabs>
                <islink>0</islink>
                <linkeditem></linkeditem>
                <customfields>
                    <field>
                        <name>IDS_IdentityName</name>
                        <value>account-name/id</value>
                        <visible>-1</visible>
                        <kind>0</kind>
                        <type>0</type>
                    </field>
                    <field>
                        <name>IDS_IdentityEmail</name>
                        <value>email</value>
                        <visible>-1</visible>
                        <kind>0</kind>
                        <type>0</type>
                    </field>
                    <field>
                        <name>IDS_IdentityFirstName</name>
                        <value>firstName</value>
                        <visible>-1</visible>
                        <kind>0</kind>
                        <type>0</type>
                    </field>
                    <field>
                        <name>IDS_IdentityLastName</name>
                        <value>surName</value>
                        <visible>-1</visible>
                        <kind>0</kind>
                        <type>0</type>
                    </field>
                    <field>
                        <name>IDS_IdentityCompany</name>
                        <value>someCompany</value>
                        <visible>-1</visible>
                        <kind>0</kind>
                        <type>0</type>
                    </field>
                    <field>
                        <name>IDS_IdentityAddress1</name>
                        <value>someStreet</value>
                        <visible>-1</visible>
                        <kind>0</kind>
                        <type>0</type>
                    </field>
                    <field>
                        <name>IDS_IdentityAddress2</name>
                        <value>address 2</value>
                        <visible>-1</visible>
                        <kind>0</kind>
                        <type>0</type>
                    </field>
                    <field>
                        <name>IDS_IdentityCity</name>
                        <value>town</value>
                        <visible>-1</visible>
                        <kind>0</kind>
                        <type>0</type>
                    </field>
                    <field>
                        <name>IDS_IdentityState</name>
                        <value>state</value>
                        <visible>-1</visible>
                        <kind>0</kind>
                        <type>0</type>
                    </field>
                    <field>
                        <name>IDS_IdentityZIP</name>
                        <value>zipCode</value>
                        <visible>-1</visible>
                        <kind>0</kind>
                        <type>0</type>
                    </field>
                    <field>
                        <name>IDS_IdentityCountry</name>
                        <value>country</value>
                        <visible>-1</visible>
                        <kind>0</kind>
                        <type>0</type>
                    </field>
                    <field>
                        <name>IDS_IdentityPhone</name>
                        <value>phoneNumber</value>
                        <visible>-1</visible>
                        <kind>0</kind>
                        <type>0</type>
                    </field>
                    <field>
                        <name>IDS_IdentityWebsite</name>
                        <value>website</value>
                        <visible>-1</visible>
                        <kind>0</kind>
                        <type>8</type>
                    </field>
                    <field>
                        <name>IDS_IdentityBirthDate</name>
                        <value>45789</value>
                        <visible>-1</visible>
                        <kind>0</kind>
                        <type>3</type>
                    </field>
                    <field>
                        <name>IDS_IdentityMobile</name>
                        <value>mobileNumber</value>
                        <visible>-1</visible>
                        <kind>0</kind>
                        <type>0</type>
                    </field>
                    <field>
                        <name>IDS_IdentityFax</name>
                        <value>faxNumber</value>
                        <visible>-1</visible>
                        <kind>0</kind>
                        <type>0</type>
                    </field>
                    <field>
                        <name>IDS_IdentityHouseNumber</name>
                        <value>123</value>
                        <visible>-1</visible>
                        <kind>0</kind>
                        <type>0</type>
                    </field>
                </customfields>
            </item>
        </group>
    </passwords>
    <recyclebin>
    </recyclebin>
    <infotemplates>
    </infotemplates>
    <favorites>
        QUY3NEZGODYtRkUzOS00NTg0LThFOTYtRkU5NTBDMjg5REY4DQo=
    </favorites>
    <sitestoignore>

    </sitestoignore>
    <categories>
        QWxsZ2VtZWluDQpIb21lIEJhbmtpbmcNCkludGVybmV0DQpQcml2YXQNCldpbmRvd3MNCg==
    </categories>
</passwordfile>`;
