export const SoftwareLicenseTestData = `<?xml version="1.0" encoding="utf-8"?>
<passwordfile xmlns="https://www.password-depot.de/schemas/passwordfile/17.0/passwordfile.xsd">
    <header>
        <application>Password Depot</application>
        <version>17.0.0</version>
        <comments></comments>
        <hint></hint>
        <fingerprint>CCDA8015-7F21-4344-BDF0-9EA6AF8AE31D</fingerprint>
        <datetime fmt="dd.mm.yyyy hh:mm:ss">12.05.2025 15:16:11</datetime>
        <encrypted>False</encrypted>
        <backupinterval>0</backupinterval>
        <lastbackup fmt="dd.mm.yyyy hh:mm:ss">30.12.1899 00:00:00</lastbackup>
        <hash></hash>
    </header>
    <passwords>
        <group name="tempDB" fingerprint="CCDA8015-7F21-4344-BDF0-9EA6AF8AE31D">
            <item>
                <description>software-license type</description>
                <type>2</type>
                <password>somePassword</password>
                <username>someUserName</username>
                <url>example.com</url>
                <comment>someComment</comment>
                <lastmodified fmt="dd.mm.yyyy hh:mm:ss">12.05.2025 15:12:48</lastmodified>
                <expirydate fmt="dd.mm.yyyy">00.00.0000</expirydate>
                <importance>1</importance>
                <fingerprint>220206EB-BE82-4E78-8FFB-9316D854721F</fingerprint>
                <template></template>
                <imageindex>128</imageindex>
                <imagecustom>0</imagecustom>
                <wndtitle></wndtitle>
                <paramstr></paramstr>
                <category>Allgemein</category>
                <custombrowser></custombrowser>
                <autocompletemethod>0</autocompletemethod>
                <loginid></loginid>
                <passid></passid>
                <created fmt="dd.mm.yyyy hh:mm:ss">12.05.2025 15:11:33</created>
                <lastaccessed fmt="dd.mm.yyyy hh:mm:ss">12.05.2025 15:11:33</lastaccessed>
                <donotaddon>0</donotaddon>
                <markassafe>0</markassafe>
                <safemode>0</safemode>
                <rndtype>1</rndtype>
                <rndcustom></rndcustom>
                <usagecount>0</usagecount>
                <keephistory>2</keephistory>
                <tags></tags>
                <author>DJSMI</author>
                <ownerid></ownerid>
                <warnmsg></warnmsg>
                <warnlvl>0</warnlvl>
                <warnverify></warnverify>
                <serverrqrd>0</serverrqrd>
                <secret></secret>
                <istemplate>0</istemplate>
                <infotemplate></infotemplate>
                <usetabs>161</usetabs>
                <islink>0</islink>
                <linkeditem></linkeditem>
                <customfields>
                    <field>
                        <name>IDS_LicenseProduct</name>
                        <value>someProduct</value>
                        <visible>0</visible>
                        <kind>0</kind>
                        <type>0</type>
                    </field>
                    <field>
                        <name>IDS_LicenseVersion</name>
                        <value>someVersion</value>
                        <visible>0</visible>
                        <kind>0</kind>
                        <type>0</type>
                    </field>
                    <field>
                        <name>IDS_LicenseName</name>
                        <value>some User</value>
                        <visible>-1</visible>
                        <kind>0</kind>
                        <type>0</type>
                    </field>
                    <field>
                        <name>IDS_LicenseKey</name>
                        <value>license-key</value>
                        <visible>-1</visible>
                        <kind>0</kind>
                        <type>0</type>
                    </field>
                    <field>
                        <name>IDS_LicenseAdditionalKey</name>
                        <value>additional-license-key</value>
                        <visible>-1</visible>
                        <kind>0</kind>
                        <type>0</type>
                    </field>
                    <field>
                        <name>IDS_LicenseURL</name>
                        <value>example.com</value>
                        <visible>-1</visible>
                        <kind>0</kind>
                        <type>8</type>
                    </field>
                    <field>
                        <name>IDS_LicenseProtected</name>
                        <value>1</value>
                        <visible>0</visible>
                        <kind>0</kind>
                        <type>5</type>
                    </field>
                    <field>
                        <name>IDS_LicenseUserName</name>
                        <value>someUserName</value>
                        <visible>-1</visible>
                        <kind>0</kind>
                        <type>0</type>
                    </field>
                    <field>
                        <name>IDS_LicensePassword</name>
                        <value>somePassword</value>
                        <visible>-1</visible>
                        <kind>0</kind>
                        <type>1</type>
                    </field>
                    <field>
                        <name>IDS_LicensePurchaseDate</name>
                        <value>45789</value>
                        <visible>0</visible>
                        <kind>0</kind>
                        <type>3</type>
                    </field>
                    <field>
                        <name>IDS_LicenseOrderNumber</name>
                        <value>order number</value>
                        <visible>-1</visible>
                        <kind>0</kind>
                        <type>0</type>
                    </field>
                    <field>
                        <name>IDS_LicenseEmail</name>
                        <value>someEmail</value>
                        <visible>-1</visible>
                        <kind>0</kind>
                        <type>7</type>
                    </field>
                    <field>
                        <name>IDS_LicenseExpires</name>
                        <value>Nie</value>
                        <visible>0</visible>
                        <kind>0</kind>
                        <type>3</type>
                    </field>
                </customfields>
            </item>            
        </group>
    </passwords>
    <recyclebin>
    </recyclebin>
    <infotemplates>
    </infotemplates>
    <favorites>
        QUY3NEZGODYtRkUzOS00NTg0LThFOTYtRkU5NTBDMjg5REY4DQo=
    </favorites>
    <sitestoignore>

    </sitestoignore>
    <categories>
        QWxsZ2VtZWluDQpIb21lIEJhbmtpbmcNCkludGVybmV0DQpQcml2YXQNCldpbmRvd3MNCg==
    </categories>
</passwordfile>`;
