name: Autofill BIT checks
run-name: Autofill BIT checks on ${{ github.event.workflow_run.head_branch }} build

on:
  workflow_run:
    workflows: ["Build Browser"]
    types:
      - completed

jobs:
  check-files:
    name: Check files
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      actions: write
      contents: read
      id-token: write
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Check for job requirements
      if: ${{ !github.event.workflow_run.pull_requests || !github.event.workflow_run.head_branch }}
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh run cancel ${{ github.run_id }}
        gh run watch ${{ github.run_id }}

    - name: Log in to Azure
      uses: bitwarden/gh-actions/azure-login@main
      with:
        subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        client_id: ${{ secrets.AZURE_CLIENT_ID }}

    - name: Get Azure Key Vault secrets
      id: get-kv-secrets
      uses: bitwarden/gh-actions/get-keyvault-secrets@main
      with:
        keyvault: gh-org-bitwarden
        secrets: "BW-GHAPP-ID,BW-GHAPP-KEY"

    - name: Log out from Azure
      uses: bitwarden/gh-actions/azure-logout@main

    - name: Generate GH App token
      uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
      id: app-token
      with:
        app-id: ${{ steps.get-kv-secrets.outputs.BW-GHAPP-ID }}
        private-key: ${{ steps.get-kv-secrets.outputs.BW-GHAPP-KEY }}
        owner: bitwarden
        repositories: browser-interactions-testing
        permission-actions: write

    - name: Get changed files
      id: changed-files
      uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
      with:
        list-files: shell
        ref: ${{ github.event.workflow_run.head_branch }}
        token: ${{ secrets.GITHUB_TOKEN }}
        filters: |
          monitored:
            - 'apps/browser/src/autofill/**'
            - 'apps/browser/src/background/**'
            - 'apps/browser/src/platform/services/browser-script-injector.service.ts'

    - name: Trigger test-all workflow in browser-interactions-testing
      if: steps.changed-files.outputs.monitored == 'true'
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
        ORIGIN_ISSUE: ${{ github.event.workflow_run.pull_requests[0].number }}
        ORIGIN_BRANCH: ${{ github.event.workflow_run.pull_requests[0].head.ref }}
      run: |
        gh workflow run test-all.yml \
          --repo bitwarden/browser-interactions-testing \
          --field CLIENTS_BRANCH="$ORIGIN_BRANCH" \
          --field origin_issue="$ORIGIN_ISSUE"
        gh workflow run test-all-custom-flags.yml \
          --repo bitwarden/browser-interactions-testing \
          --field CLIENTS_BRANCH="$ORIGIN_BRANCH" \
          --field origin_issue="$ORIGIN_ISSUE"
