name: Auto Bump Desktop Version

on:
  push:
    tags:
      - desktop-v**

permissions: {}

jobs:
  trigger:
    name: Trigger version-auto-bump-desktop
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    steps:
      - name: Trigger deployment
        uses: bitwarden/gh-actions/trigger-actions@main
        with:
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          task: version-auto-bump-desktop
